ip_address: 192.168.1.100
synced_folders:
  user:
    source: 'D:\Users\FRUP67305' # absolute or relative path from Vagrantfile
    target: '/D/Users/FRUP67305' # absolute or relative path from home of VM
  project:
    source: 'C:\' # absolute or relative path from Vagrantfile
    target: '/C' # absolute or relative path from home of VM
